theme: jekyll-theme-architect

title: 'PADRE'
description: 'Performance-driven softwAre moDel Refactoring framEwork'

show_downloads: 'true'

relative_links:
  enabled: true
  collections: false

github:
  padre: 'https://github.com/SEALABQualityGroup/padre'
  tar_url: 'https://github.com/SEALABQualityGroup/padre/archive/v1.0.1.tar.gz'
  zip_url: 'https://github.com/SEALABQualityGroup/padre/archive/v1.0.1.zip'

plugins:
  - jekyll-relative-links
  
markdown: kramdown
